---
Theme:
  # The name of the image you wish to use as the background
  # Must be located in the assets/images/ directory
  # Set to "" to have the background colour as the background instead
  backgroundImage: ""
  # Colours in (r, g, b) format
  Colours:
    primary: (108, 204, 98)
    secondary: (98, 204, 141)
    background: (0, 0, 0)
  Font:
    # If true the global font will be used for all services
    useGlobal: false
    # The name of the ttf font file you wish to use
    # *.ttf files must be located in the assets/fonts/ directory
    globalFont: "embodial.ttf"
    clockFont: "apollo.ttf"
    clockFontSize: 100
    deviceInfoFont: "apollo.ttf"
    deviceInfoFontSize: 25
---
Services:
  Clock:
    enabled: true
    # Format of the clock: %d/%m/%Y %H:%M:%S
    format: "%H:%M"
    x: 10
    y: 220
  DeviceInfo:
    enabled: true
    # Space between each line
    lineHeight: 30
    x: 10
    y: 10
  Music:
    enabled: false
    # Name of the icon located in assets/icons/
    playIcon: "play.png"
    pauseIcon: "pause.png"
    btnX: 390
    btnY: 220
    # Name of music files located in assets/music/
    # Plays in order from top to bottom
    # Formats supported: all which are supported by pygame
    playlist:
      - "1.mp3"
      - "2.mp3"
      - "3.mp3"
      - "4.mp3"
  Games:
    enabled: true
    # Name of the icon located in assets/icons/
    icon: "games.png"
    iconX: 438
    iconY: 10
    crossIcon: "cross.png"
    crossX: 10
    crossY: 10
---
Settings:
  fps: 30
...
